CREATE TABLE newvendor (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    vendor TEXT NOT NULL,
    item_name TEXT NOT NULL,
    description TEXT NOT NULL,
    price TEXT NOT NULL,
    availbility TEXT NOT NULL   
);