CREATE TABLE newVendor (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    item_name TEXT NOT NULL,
    summary TEXT NOT NULL,
    price MONEY NOT NULL,
    availbility TEXT NOT NULL,
    vendor TEXT NOT NULL
);